apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: provider-gcp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rezamt/crossplane-workshop
    path: 02-argocd/providers/gcp
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
